--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/28/2022 3:56:38 PM
-- Server version: 8.0.30
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE `misa.dmviet`;

--
-- Drop table `roledetail`
--
DROP TABLE IF EXISTS roledetail;

--
-- Drop table `role`
--
DROP TABLE IF EXISTS role;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Set default database
--
USE `misa.dmviet`;

--
-- Create table `department`
--
CREATE TABLE department (
  DepartmentID char(36) NOT NULL DEFAULT '' COMMENT 'Khoá chính',
  DepartmentCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã phòng ban',
  DepartmentName varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên phòng ban',
  CraeteBy varchar(100) DEFAULT NULL COMMENT 'Người tạo',
  CreateDate datetime DEFAULT NULL COMMENT 'Thời gian tạo',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người sửa',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Thời gian sửa',
  PRIMARY KEY (DepartmentID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Phòng ban';

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeID char(36) NOT NULL DEFAULT '' COMMENT 'Khoá chính',
  EmployeeCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã nhân viên',
  EmployeeName varchar(100) NOT NULL DEFAULT '' COMMENT 'Họ và tên',
  DepartmentID char(36) NOT NULL DEFAULT '',
  Email varchar(100) NOT NULL DEFAULT '' COMMENT 'Email',
  EmployeeStatus int NOT NULL COMMENT 'Trạng thái',
  CreateBy varchar(100) DEFAULT NULL COMMENT 'Người tạo',
  CreateDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người sửa',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  PRIMARY KEY (EmployeeID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Nhân viên';

--
-- Create index `UK_employee_EmployeeCode` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX UK_employee_EmployeeCode (EmployeeCode);

--
-- Create index `UK_employee_EmployeeName` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX UK_employee_EmployeeName (EmployeeName);

--
-- Create foreign key
--
ALTER TABLE employee
ADD CONSTRAINT FK_employee_DepartmentID FOREIGN KEY (DepartmentID)
REFERENCES department (DepartmentID);

--
-- Create table `role`
--
CREATE TABLE role (
  RoleID char(36) NOT NULL DEFAULT '' COMMENT 'Khoá chính',
  RoleName varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên vai trò',
  RoleDescription varchar(255) NOT NULL DEFAULT '' COMMENT 'Mô tả vai trò',
  CreateBy varchar(100) DEFAULT NULL COMMENT 'Người tạo',
  CreateDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người sửa',
  ModifiedDate datetime DEFAULT NULL,
  PRIMARY KEY (RoleID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Vai trò';

--
-- Create table `roledetail`
--
CREATE TABLE roledetail (
  EmployeeID char(36) NOT NULL DEFAULT '' COMMENT 'ID nhân viên',
  RoleID char(36) NOT NULL DEFAULT ''
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Chi tiết vai trò công việc';

--
-- Create foreign key
--
ALTER TABLE roledetail
ADD CONSTRAINT FK_roledetail_EmployeeID FOREIGN KEY (EmployeeID)
REFERENCES employee (EmployeeID);

--
-- Create foreign key
--
ALTER TABLE roledetail
ADD CONSTRAINT FK_roledetail_RoleID FOREIGN KEY (RoleID)
REFERENCES role (RoleID);

-- 
-- Dumping data for table department
--
-- Table `misa.dmviet`.department does not contain any data (it is empty)

-- 
-- Dumping data for table role
--
-- Table `misa.dmviet`.role does not contain any data (it is empty)

-- 
-- Dumping data for table employee
--
-- Table `misa.dmviet`.employee does not contain any data (it is empty)

-- 
-- Dumping data for table roledetail
--
-- Table `misa.dmviet`.roledetail does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;